### ISSUE TITLE
TypeError: this.func.prependArg is not a function in strophe.flxhr.js

### ISSUE THREAD

**Issue by onclave** [metajack/profxmpp#3]
I have bought the book and I am going through Chapter 3 - SAYING HELLO: THE FIRST APPLICATION. Under hello.js (initial version), it is giving me an error 'TypeError: this.func.prependArg is not a function in strophe.flxhr.js' in my FireFox Web Console. What wrong am I doing?

**Comment by metajack** [comment]
Please remove strophe.flxhr.js from the code. It no longer works.

**Comment by onclave** [comment]
Will all the code in the rest of the book run without this file included? I also found a newer version of this file here (https://github.com/strophe/strophejs-plugins/tree/master/flxhr), should I use that, or completely remove this file?

**Comment by metajack** [comment]
If you can get the newer file to work, go for it.

strophe.flxhr.js just makes some testing easier as it relaxes the CORS requirement by using Flash instead. Most things support CORS natively now, so it is probably not needed anyway. It doesn't provide any APIs or anything that are needed by the example code; it's purely an alternate implementation of XMLHttpRequest.

**Comment by onclave** [comment]
Thank you so much for your reply. Just one more help I require. I have a few problems I am facing while testing the code from the book. StackOverflow is really not helping me in this. It would be great if you could guide me a bit about my problems. Should I post them here, or should I go to the wrox website and post there? Thank you.

**Comment by metajack** [comment]
I suggest posting on the strophe mailing list: https://groups.google.com/forum/#!forum/strophe

**Comment by onclave** [comment]
Thank you for the advice. :)
